name: respirometry
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - opencv
  - svgpath2mpl
  - scipy
  - statsmodels
  - jupyter
  - jupyterlab
  - ipykernel
  - r-base
  - r-dplyr
  - r-readr
  - r-respirometry

# Usage:
#   conda env create -f environment.yml
#   conda activate respirometry
#   python -m ipykernel install --user --name "respirometry" --display-name "Python (conda: respirometry)"
